# Group By

In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('data/fortune1000.csv', index_col='Rank')
data.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [11]:
sectors = data.groupby('Sector') # creating a DataFrameGroupBy object

In [12]:
sectors.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
6,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",157107,5813,200000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
9,Ford Motor,Motor Vehicles & Parts,Motor Vehicles and Parts,"Dearborn, MI",149558,7373,199000
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
12,AmerisourceBergen,Health Care,Wholesalers: Health Care,"Chesterbrook, PA",135962,-135,17000
13,Verizon,Telecommunications,Telecommunications,"New York, NY",131620,17879,177700
14,Chevron,Energy,Petroleum Refining,"San Ramon, CA",131118,4587,61500
15,Costco,Retailing,Specialty Retailers: Other,"Issaquah, WA",116199,2377,161000
16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
17,Kroger,Food and Drug Stores,Food and Drug Stores,"Cincinnati, OH",109830,2039,431000
18,Amazon.com,Technology,Internet Services and Retailing,"Seattle, WA",107006,596,230800
19,Walgreens Boots Alliance,Food and Drug Stores,Food and Drug Stores,"Deerfield, IL",103444,4220,302500
20,HP,Technology,"Computers, Office Equipment","Palo Alto, CA",103355,4554,287000
21,Cardinal Health,Health Care,Wholesalers: Health Care,"Dublin, OH",102531,1215,34500
22,Express Scripts Holding,Health Care,Health Care: Pharmacy and Other Services,"St. Louis, MO",101752,2476,25900
23,J.P. Morgan Chase,Financials,Commercial Banks,"New York, NY",101006,24442,234598
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
25,Microsoft,Technology,Computer Software,"Redmond, WA",93580,12193,118000
26,Bank of America Corp.,Financials,Commercial Banks,"Charlotte, NC",93056,15888,213280
27,Wells Fargo,Financials,Commercial Banks,"San Francisco, CA",90033,22894,264700
28,Home Depot,Retailing,Specialty Retailers: Other,"Atlanta, GA",88519,7009,385000
30,Phillips 66,Energy,Petroleum Refining,"Houston, TX",87169,4227,14000
31,IBM,Technology,Information Technology Services,"Armonk, NY",82461,13190,411798
...,...,...,...,...,...,...,...
151,Kimberly-Clark,Household Products,Household and Personal Products,"Irving, TX",18591,1013,43000
154,Lear,Motor Vehicles & Parts,Motor Vehicles and Parts,"Southfield, MI",18211,746,136200
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
156,AECOM,Engineering & Construction,"Engineering, Construction","Los Angeles, CA",17990,-155,92000
159,CenturyLink,Telecommunications,Telecommunications,"Monroe, LA",17900,878,43000
170,Nucor,Materials,Metals,"Charlotte, NC",16439,358,23700
174,Colgate-Palmolive,Household Products,Household and Personal Products,"New York, NY",16034,1384,37900
182,PPG Industries,Chemicals,Chemicals,"Pittsburgh, PA",15330,1406,46600
186,Omnicom Group,Business Services,"Advertising, marketing","New York, NY",15134,1094,74900
189,Monsanto,Chemicals,Chemicals,"St. Louis, MO",15001,2314,24000
195,Marriott International,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Bethesda, MD",14486,859,127500
199,Aramark,Business Services,Diversified Outsourcing Services,"Philadelphia, PA",14329,236,216500
203,CBS,Media,Entertainment,"New York, NY",13886,1413,19080
204,Visa,Business Services,Financial Data Services,"Foster City, CA",13880,6328,11300
206,Ecolab,Chemicals,Chemicals,"St. Paul, MN",13545,1002,47145
213,Viacom,Media,Entertainment,"New York, NY",13268,1922,9445
218,Yum Brands,"Hotels, Resturants & Leisure",Food Services,"Louisville, KY",13105,1293,505000
221,Waste Management,Business Services,Waste Management,"Houston, TX",12961,753,40600
231,VF,Apparel,Apparel,"Greensboro, NC",12377,1232,64000
235,Jacobs Engineering Group,Engineering & Construction,"Engineering, Construction","Pasadena, CA",12115,303,56950
241,Las Vegas Sands,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Las Vegas, NV",11689,1966,46500
244,United States Steel,Materials,Metals,"Pittsburgh, PA",11574,-1642,33200
251,WestRock,Materials,"Packaging, Containers","Richmond, VA",11381,507,41400
256,Stanley Black & Decker,Household Products,"Home Equipment, Furnishings","New Britain, CT",11211,884,51250
260,D.R. Horton,Engineering & Construction,Homebuilders,"Fort Worth, TX",10824,751,6230
261,Estee Lauder,Household Products,Household and Personal Products,"New York, NY",10780,1089,44000
301,Lennar,Engineering & Construction,Homebuilders,"Miami, FL",9474,803,7749
340,PVH,Apparel,Apparel,"New York, NY",8020,572,26200
354,Ralph Lauren,Apparel,Apparel,"New York, NY",7620,702,20000
448,Hanesbrands,Apparel,Apparel,"Winston-Salem, NC",5732,429,65300

In [13]:
data.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [14]:
print type(data)
print type(sectors)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.groupby.DataFrameGroupBy'>

In [16]:
print len(data)
print len(sectors) # data frame for each sector

1000
21

In [18]:
data['Sector'].nunique()

21

In [22]:
sectors.size() # occurrences of each sector
# data['Sector'].value_counts()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [26]:
sectors.first() # first occurence of each grouping

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,"Chicago, IL",96114,5176,161400
Apparel,Nike,Apparel,"Beaverton, OR",30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,"Milwaukee, WI",19330,419,27000
Chemicals,Dow Chemical,Chemicals,"Midland, MI",48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,"Irving, TX",246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction","Irving, TX",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,"Chicago, IL",67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,"Oak Brook, IL",25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
Industrials,General Electric,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
Materials,Alcoa,Metals,"New York, NY",22534,-322,60000
Media,Disney,Entertainment,"Burbank, CA",52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
Retailing,Walmart,General Merchandisers,"Bentonville, AR",482130,14694,2300000
Technology,Apple,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
Telecommunications,AT&T,Telecommunications,"Dallas, TX",146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [27]:
sectors.last() # last occurence of each grouping

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Delta Tucker Holdings,Aerospace and Defense,"McLean, VA",1923,-133,12000
Apparel,Guess,Apparel,"Los Angeles, CA",2204,82,13500
Business Services,DeVry Education Group,Education,"Downers Grove, IL",1910,140,11770
Chemicals,H.B. Fuller,Chemicals,"St. Paul, MN",2084,87,4425
Energy,Portland General Electric,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
Engineering & Construction,MDC Holdings,Homebuilders,"Denver, CO",1909,66,1225
Financials,New York Community Bancorp,Commercial Banks,"Westbury, NY",1902,-47,3448
Food and Drug Stores,Fred’s,Food and Drug Stores,"Memphis, TN",2151,-7,7103
"Food, Beverages & Tobacco",Alliance One International,Tobacco,"Morrisville, NC",2066,-15,6835
Health Care,Providence Service,Health Care: Pharmacy and Other Services,"Tucson, AZ",1987,84,9072
"Hotels, Resturants & Leisure",Wendy’s,Food Services,"Dublin, OH",1896,161,21200
Household Products,Revlon,Household and Personal Products,"New York, NY",1914,56,5700
Industrials,Briggs & Stratton,Industrial Machinery,"Wauwatosa, WI",1895,46,5480
Materials,Schnitzer Steel Industries,Metals,"Portland, OR",1924,-197,2955
Media,Cenveo,"Publishing, Printing","Stamford, CT",1921,-31,7300
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,"Indianaoplis, IN",1986,182,2700
Retailing,99 Cents Only Stores,Specialty Retailers: Other,"Commerce, CA",1999,-232,18200
Technology,F5 Networks,Network and Other Communications Equipment,"Seattle, WA",1920,365,4178
Telecommunications,Equinix,Telecommunications,"Redwood City, CA",2726,188,5042
Transportation,Roadrunner Transportation Systems,Transportation and Logistics,"Cudahy, WI",1995,48,4502
Wholesalers,BlueLinx Holdings,Wholesalers: Diversified,"Atlanta, GA",1917,-12,1600

In [34]:
sectors.groups # Dict
# sectors.groups.keys() one key for each sector
# sectors.groups.values() List of Index

{'Aerospace & Defense': Int64Index([ 24,  45,  60,  88, 118, 120, 209, 245, 282, 378, 389, 490, 560,
             605, 785, 788, 836, 903, 958, 987],
            dtype='int64', name=u'Rank'),
 'Apparel': Int64Index([91, 231, 340, 354, 448, 547, 575, 597, 683, 695, 726, 794, 877,
             882, 917],
            dtype='int64', name=u'Rank'),
 'Business Services': Int64Index([144, 186, 199, 204, 221, 248, 249, 294, 307, 312, 355, 392, 404,
             440, 467, 468, 481, 485, 492, 503, 545, 626, 635, 652, 677, 694,
             714, 729, 734, 735, 737, 744, 767, 776, 777, 783, 791, 792, 796,
             801, 803, 816, 819, 820, 869, 870, 886, 939, 951, 952, 993],
            dtype='int64', name=u'Rank'),
 'Chemicals': Int64Index([ 56, 101, 182, 189, 206, 253, 262, 277, 288, 296, 316, 538, 549,
             555, 566, 580, 613, 624, 654, 668, 717, 720, 724, 758, 761, 829,
             865, 898, 934, 949],
            dtype='int64', name=u'Rank'),
 'Energy': Int64Index([  2,  14,  30,  32,  42,  65,  90,  95,  98, 104,
             ...
             953, 955, 962, 966, 980, 981, 983, 995, 997, 997],
            dtype='int64', name=u'Rank', length=122),
 'Engineering & Construction': Int64Index([155, 156, 235, 260, 301, 314, 352, 381, 433, 478, 498, 501, 516,
             572, 576, 640, 719, 738, 822, 863, 874, 892, 929, 963, 985, 994],
            dtype='int64', name=u'Rank'),
 'Financials': Int64Index([  4,  16,  23,  26,  27,  29,  35,  40,  43,  49,
             ...
             920, 923, 925, 926, 936, 938, 959, 976, 988, 996],
            dtype='int64', name=u'Rank', length=139),
 'Food and Drug Stores': Int64Index([7, 17, 19, 87, 107, 160, 181, 595, 614, 631, 669, 756, 809, 849,
             928],
            dtype='int64', name=u'Rank'),
 'Food, Beverages & Tobacco': Int64Index([ 41,  44,  62,  66,  84,  94, 106, 149, 153, 161, 176, 207, 215,
             242, 266, 304, 336, 337, 362, 397, 413, 429, 452, 456, 460, 535,
             542, 567, 574, 587, 608, 615, 636, 664, 686, 702, 770, 787, 795,
             804, 889, 902, 954],
            dtype='int64', name=u'Rank'),
 'Health Care': Int64Index([  5,   6,  12,  21,  22,  33,  39,  46,  52,  55,  63,  72,  79,
              86, 123, 124, 125, 130, 138, 140, 141, 168, 172, 200, 201, 202,
             263, 268, 278, 286, 287, 290, 291, 305, 325, 358, 359, 372, 420,
             430, 431, 447, 457, 465, 469, 515, 527, 537, 553, 559, 583, 618,
             629, 661, 684, 693, 697, 708, 746, 749, 766, 775, 790, 799, 815,
             818, 845, 868, 881, 883, 935, 960, 965, 977, 978],
            dtype='int64', name=u'Rank'),
 'Hotels, Resturants & Leisure': Int64Index([109, 146, 195, 218, 241, 254, 309, 371, 444, 466, 534, 546, 557,
             562, 585, 731, 763, 764, 779, 797, 895, 915, 918, 941, 999],
            dtype='int64', name=u'Rank'),
 'Household Products': Int64Index([ 34, 151, 174, 256, 261, 328, 338, 345, 370, 434, 441, 450, 455,
             533, 550, 554, 601, 665, 699, 716, 856, 890, 900, 907, 932, 950,
             967, 992],
            dtype='int64', name=u'Rank'),
 'Industrials': Int64Index([  11,   59,   75,   93,   97,  128,  134,  148,  211,  224,  360,
              377,  396,  412,  419,  539,  544,  596,  622,  623,  630,  645,
              655,  658,  666,  674,  690,  757,  782,  789,  806,  813,  823,
              831,  832,  835,  841,  847,  866,  867,  873,  887,  942,  947,
              964, 1000],
            dtype='int64', name=u'Rank'),
 'Materials': Int64Index([126, 127, 170, 244, 251, 303, 321, 341, 356, 373, 375, 383, 417,
             418, 426, 435, 446, 480, 489, 514, 518, 577, 586, 616, 617, 620,
             625, 628, 637, 639, 641, 660, 667, 687, 691, 751, 774, 793, 857,
             885, 911, 982, 986],
            dtype='int64', name=u'Rank'),
 'Media': Int64Index([ 53,  96,  99, 203, 213, 255, 327, 366, 406, 414, 525, 530, 681,
             705, 707, 722, 741, 752, 759, 762, 821, 913, 968, 969, 989],
            dtype='int64', name=u'Rank'),
 'Motor Vehicles & Parts': Int64Index([  8,   9,  70, 147, 154, 169, 281, 310, 334, 339, 424, 428, 470,
             588, 591, 604, 647, 670, 718, 739, 811, 957, 961, 979],
            dtype='int64', name=u'Rank'),
 'Retailing': Int64Index([  1,  15,  28,  38,  47,  71,  89, 103, 111, 132, 136, 139, 143,
             145, 177, 180, 191, 196, 197, 228, 234, 237, 238, 240, 258, 267,
             269, 280, 293, 297, 299, 302, 330, 342, 346, 361, 365, 374, 379,
             380, 393, 415, 427, 439, 495, 500, 502, 511, 512, 517, 523, 582,
             592, 602, 607, 610, 621, 643, 644, 648, 657, 675, 689, 721, 748,
             771, 773, 807, 812, 824, 825, 827, 840, 876, 894, 899, 922, 937,
             940, 973],
            dtype='int64', name=u'Rank'),
 'Technology': Int64Index([  3,  18,  20,  25,  31,  36,  51,  54,  77, 110,
             ...
             931, 943, 944, 946, 956, 970, 971, 975, 984, 990],
            dtype='int64', name=u'Rank', length=102),
 'Telecommunications': Int64Index([10, 13, 37, 116, 159, 187, 292, 333, 399, 443, 461, 496, 526, 619,
             786],
            dtype='int64', name=u'Rank'),
 'Transportation': Int64Index([ 48,  58,  67,  68,  80, 129, 142, 208, 239, 270, 353, 390, 395,
             405, 407, 416, 432, 459, 521, 528, 570, 578, 642, 672, 709, 713,
             740, 800, 814, 858, 884, 930, 933, 945, 972, 974],
            dtype='int64', name=u'Rank'),
 'Wholesalers': Int64Index([ 57,  64,  92, 102, 108, 119, 122, 167, 183, 185, 212, 276, 285,
             315, 317, 320, 323, 335, 351, 357, 369, 391, 423, 463, 474, 477,
             484, 564, 581, 599, 627, 653, 685, 727, 747, 780, 808, 837, 875,
             991],
            dtype='int64', name=u'Rank')}

In [37]:
data.loc[24]

Company                     Boeing
Sector         Aerospace & Defense
Industry     Aerospace and Defense
Location               Chicago, IL
Revenue                      96114
Profits                       5176
Employees                   161400
Name: 24, dtype: object

## Get Group

In [40]:
sectors.get_group(name='Apparel') # return a dataframe

,Company,Employees,Industry,Location,Profits,Revenue
Rank,,,,,,
91,Nike,62600,Apparel,"Beaverton, OR",3273,30601
231,VF,64000,Apparel,"Greensboro, NC",1232,12377
340,PVH,26200,Apparel,"New York, NY",572,8020
354,Ralph Lauren,20000,Apparel,"New York, NY",702,7620
448,Hanesbrands,65300,Apparel,"Winston-Salem, NC",429,5732
547,Levi Strauss,12500,Apparel,"San Francisco, CA",209,4495
575,Coach,12950,Apparel,"New York, NY",402,4192
597,Under Armour,9600,Apparel,"Baltimore, MD",233,3963
683,Fossil Group,15100,Apparel,"Richardson, TX",221,3229
695,Skechers U.S.A.,6400,Apparel,"Manhattan Beach, CA",232,3159
726,Carter’s,16800,Apparel,"Atlanta, GA",238,3014
794,Wolverine World Wide,6550,Apparel,"Rockford, MI",123,2692
877,G-III Apparel Group,8919,Apparel,"New York, NY",114,2344
882,Columbia Sportswear,5978,Apparel,"Portland, OR",174,2326
917,Guess,13500,Apparel,"Los Angeles, CA",82,2204

In [43]:
sectors.get_group(name='Energy')

,Company,Employees,Industry,Location,Profits,Revenue
Rank,,,,,,
2,Exxon Mobil,75600,Petroleum Refining,"Irving, TX",16150,246204
14,Chevron,61500,Petroleum Refining,"San Ramon, CA",4587,131118
30,Phillips 66,14000,Petroleum Refining,"Houston, TX",4227,87169
32,Valero Energy,10103,Petroleum Refining,"San Antonio, TX",3990,81824
42,Marathon Petroleum,45440,Petroleum Refining,"Findlay, OH",2852,64566
65,Energy Transfer Equity,30078,Pipelines,"Dallas, TX",1189,42126
90,ConocoPhillips,15900,"Mining, Crude-Oil Production","Houston, TX",-4428,30935
95,Exelon,29762,Utilities: Gas and Electric,"Chicago, IL",2269,29447
98,Tesoro,6016,Petroleum Refining,"San Antonio, TX",1540,28150
104,Enterprise Products Partners,6800,Pipelines,"Houston, TX",2521,27028
115,Duke Energy,29188,Utilities: Gas and Electric,"Charlotte, NC",2816,24002
117,Halliburton,65000,"Oil and Gas Equipment, Services","Houston, TX",-671,23633
121,Plains GP Holdings,5400,Pipelines,"Houston, TX",118,23152
162,Southern,26703,Utilities: Gas and Electric,"Atlanta, GA",2367,17489
163,NextEra Energy,14300,Utilities: Gas and Electric,"Juno Beach, FL",2752,17486
165,American Electric Power,17405,Utilities: Gas and Electric,"Columbus, OH",2047,16900
166,PG&E Corp.,23323,Utilities: Gas and Electric,"San Francisco, CA",874,16833
175,Freeport-McMoRan,34500,"Mining, Crude-Oil Production","Phoenix, AZ",-12236,15877
178,Baker Hughes,43000,"Oil and Gas Equipment, Services","Houston, TX",-1967,15742
188,FirstEnergy,15781,Utilities: Gas and Electric,"Akron, OH",578,15026
190,AES,21000,Utilities: Gas and Electric,"Arlington, VA",306,14963
192,National Oilwell Varco,47262,"Oil and Gas Equipment, Services","Houston, TX",-769,14757
193,NRG Energy,10468,Energy,"Princeton, NJ",-6382,14674
198,Kinder Morgan,11290,Pipelines,"Houston, TX",253,14403
214,HollyFrontier,2704,Petroleum Refining,"Dallas, TX",740,13238
216,Devon Energy,5167,"Mining, Crude-Oil Production","Oklahoma City, OK",-14454,13145
217,PBF Energy,2270,Petroleum Refining,"Parsippany, NJ",146,13124
223,Chesapeake Energy,4400,"Mining, Crude-Oil Production","Oklahoma City, OK",-14685,12764
225,Occidental Petroleum,11100,"Mining, Crude-Oil Production","Houston, TX",-7829,12699
229,Consolidated Edison,14806,Utilities: Gas and Electric,"New York, NY",1193,12554
...,...,...,...,...,...,...
784,New Jersey Resources,991,Energy,"Wall, NJ",181,2734
798,Continental Resources,1143,"Mining, Crude-Oil Production","Oklahoma City, OK",-354,2680
802,WGL Holdings,1529,Energy,"Washington, DC",131,2660
810,Crestwood Equity Partners,1300,Energy,"Houston, TX",-1667,2633
817,Hawaiian Electric Industries,3918,Utilities: Gas and Electric,"Honolulu, HI",160,2603
826,Arch Coal,4655,"Mining, Crude-Oil Production","St. Louis, MO",-2913,2573
843,Great Plains Energy,2899,Utilities: Gas and Electric,"Kansas City, MO",213,2502
850,United Refining,2997,Petroleum Refining,"Warren, PA",82,2470
851,Southwest Gas,5876,Utilities: Gas and Electric,"Las Vegas, NV",138,2464
853,Westar Energy,2330,Utilities: Gas and Electric,"Topeka, KS",292,2459
855,Vectren,5600,Utilities: Gas and Electric,"Evansville, IN",197,2435
859,Enable Midstream Partners,1640,Pipelines,"Oklahoma City, OK",-752,2418
860,Cliffs Natural Resources,2638,"Mining, Crude-Oil Production","Cleveland, OH",-749,2418
862,California Resources,1700,"Mining, Crude-Oil Production","Los Angeles, CA",-3554,2403
879,EQT,1914,Energy,"Pittsburgh, PA",85,2340
901,Alliance Holdings,4243,"Mining, Crude-Oil Production","Tulsa, OK",211,2273
908,Genesis Energy,1400,Pipelines,"Houston, TX",423,2247
921,OGE Energy,2586,Utilities: Gas and Electric,"Oklahoma City, OK",271,2197
924,Magellan Midstream Partners,1640,Pipelines,"Tulsa, OK",819,2189
948,NuStar Energy,1644,Pipelines,"San Antonio, TX",307,2084
953,Par Pacific Holdings,744,Petroleum Refining,"Houston, TX",-40,2066
955,Whiting Petroleum,1200,"Mining, Crude-Oil Production","Denver, CO",-2219,2051
962,Ferrellgas Partners,4028,Energy,"Overland Park, KS",30,2024
966,QEP Resources,693,"Mining, Crude-Oil Production","Denver, CO",-149,2019
980,Spire,3078,Utilities: Gas and Electric,"St. Louis, MO",137,1976
981,WPX Energy,1040,"Mining, Crude-Oil Production","Tulsa, OK",-1727,1958
983,Adams Resources & Energy,809,Petroleum Refining,"Houston, TX",-1,1944
995,EP Energy,665,"Mining, Crude-Oil Production","Houston, TX",-3748,1908
997,Portland General Electric,2646,Utilities: Gas and Electric,"Portland, OR",172,1898
997,Portland General Electric,2646,Utilities: Gas and Electric,"Portland, OR",172,1898

In [45]:
for g in sectors.groups.keys():
    print "Group: {}".format(g), sectors.get_group(g)

Group: Household Products                              Company  Employees  \
Rank
34                  Procter & Gamble     110000
151                   Kimberly-Clark      43000
174                Colgate-Palmolive      37900
256           Stanley Black & Decker      51250
261                     Estee Lauder      44000
328                           Jarden      40000
338                Mohawk Industries      34100
345                            Masco      25000
370                    Avon Products      30900
434                    Newell Brands      17200
441                        HRG Group      15922
450                           Mattel      31000
455                           Clorox       7700
533   Fortune Brands Home & Security      21400
550                           Hasbro       5000
554                             Coty       8100
601                  Leggett & Platt      20000
665                  Church & Dwight       4406
699       Tempur Sealy International       7200
716                        Steelcase      11550
856           Edgewell Personal Care       6000
890                              HNI      10200
900                Tupperware Brands      13000
907              Nu Skin Enterprises      26800
932                    Herman Miller       7510
950                    Vista Outdoor       5200
967                          Griffon       6000
992                           Revlon       5700

                             Industry          Location  Profits  Revenue
Rank
34    Household and Personal Products    Cincinnati, OH     7036    78756
151   Household and Personal Products        Irving, TX     1013    18591
174   Household and Personal Products      New York, NY     1384    16034
256       Home Equipment, Furnishings   New Britain, CT      884    11211
261   Household and Personal Products      New York, NY     1089    10780
328       Home Equipment, Furnishings    Boca Raton, FL      147     8604
338       Home Equipment, Furnishings       Calhoun, GA      615     8072
345       Home Equipment, Furnishings        Taylor, MI      355     7904
370   Household and Personal Products      New York, NY    -1149     7173
434       Home Equipment, Furnishings       Atlanta, GA      350     5972
441   Household and Personal Products      New York, NY     -557     5816
450                     Miscellaneous    El Segundo, CA      369     5703
455   Household and Personal Products       Oakland, CA      580     5666
533       Home Equipment, Furnishings     Deerfield, IL      315     4658
550                     Miscellaneous     Pawtucket, RI      452     4448
554   Household and Personal Products      New York, NY      233     4395
601       Home Equipment, Furnishings      Carthage, MO      325     3937
665   Household and Personal Products         Ewing, NJ      410     3395
699       Home Equipment, Furnishings     Lexington, KY       74     3151
716       Home Equipment, Furnishings  Grand Rapids, MI       86     3060
856   Household and Personal Products  Chesterfield, MO     -275     2421
890       Home Equipment, Furnishings     Muscatine, IA      105     2304
900   Household and Personal Products       Orlando, FL      186     2284
907   Household and Personal Products         Provo, UT      133     2247
932       Home Equipment, Furnishings       Zeeland, MI       98     2142
950                     Miscellaneous    Clearfield, UT       80     2083
967       Home Equipment, Furnishings      New York, NY       34     2016
992   Household and Personal Products      New York, NY       56     1914
Group: Transportation                                      Company  Employees  \
Rank
48                                       UPS     341240
58                                     FedEx     323035
67                   American Airlines Group     118500
68                           Delta Air Lines      82949
80               United Continental Holdings      84000
129                            Union Pacific      47457
142                       Southwest Airlines      49583
208                  C.H. Robinson Worldwide      13159
239                                      CSX      29761
270                         Norfolk Southern      30456
353                            XPO Logistics      89000
390   Expeditors International of Washington      15397
395                             Ryder System      33100
405                          JetBlue Airways      14537
407                       Trinity Industries      22030
416             J.B. Hunt Transport Services      21562
432                          Harley-Davidson       6300
459                         Alaska Air Group      13858
521                            YRC Worldwide      32000
528                       Polaris Industries       8100
570                     Swift Transportation      20900
578                                Brunswick      12607
642                                Hub Group       2633
672                          Landstar System       1223
709                                  SkyWest      18300
713                                   Amerco      18415
740                Old Dominion Freight Line      17931
800                                  ArcBest      13000
814                          Greenbrier Cos.      10689
858                     Kansas City Southern       6670
884                        Hawaiian Holdings       5548
930                                    Kirby       4200
933                          Spirit Airlines       4326
945                       Werner Enterprises      12325
972                        Genesee & Wyoming       7500
974        Roadrunner Transportation Systems       4502

                                 Industry              Location  Profits  \
Rank
48    Mail, Package, and Freight Delivery           Atlanta, GA     4844
58    Mail, Package, and Freight Delivery           Memphis, TN     1050
67                               Airlines        Fort Worth, TX     7610
68                               Airlines           Atlanta, GA     4526
80                               Airlines           Chicago, IL     7340
129                             Railroads             Omaha, NE     4772
142                              Airlines            Dallas, TX     2181
208          Transportation and Logistics      Eden Prairie, MN      510
239                             Railroads      Jacksonville, FL     1968
270                             Railroads           Norfolk, VA     1556
353          Transportation and Logistics         Greenwich, CT     -191
390          Transportation and Logistics           Seattle, WA      457
395               Trucking, Truck Leasing             Miami, FL      305
405                              Airlines  Long Island City, NY      677
407              Transportation Equipment            Dallas, TX      797
416               Trucking, Truck Leasing            Lowell, AR      427
432              Transportation Equipment         Milwaukee, WI      752
459                              Airlines           Seattle, WA      848
521               Trucking, Truck Leasing     Overland Park, KS        1
528              Transportation Equipment            Medina, MN      455
570               Trucking, Truck Leasing           Phoenix, AZ      198
578              Transportation Equipment       Lake Forest, IL      241
642          Transportation and Logistics         Oak Brook, IL       71
672               Trucking, Truck Leasing      Jacksonville, FL      148
709                              Airlines        St. George, UT      118
713               Trucking, Truck Leasing              Reno, NV      357
740               Trucking, Truck Leasing       Thomasville, NC      305
800               Trucking, Truck Leasing        Fort Smith, AR       45
814              Transportation Equipment       Lake Oswego, OR      193
858                             Railroads       Kansas City, MO      484
884                              Airlines          Honolulu, HI      183
930                         Miscellaneous           Houston, TX      227
933                              Airlines           Miramar, FL      317
945               Trucking, Truck Leasing             Omaha, NE      124
972                             Railroads            Darien, CT      225
974          Transportation and Logistics            Cudahy, WI       48

      Revenue
Rank
48      58363
58      47453
67      40990
68      40704
80      37864
129     21813
142     19820
208     13476
239     11811
270     10511
353      7623
390      6617
395      6572
405      6416
407      6393
416      6188
432      5995
459      5598
521      4832
528      4719
570      4229
578      4143
642      3526
672      3321
709      3096
713      3075
740      2972
800      2667
814      2605
858      2419
884      2318
930      2148
933      2142
945      2094
972      2000
974      1995
Group: Business Services                                      Company  Employees  \
Rank
144                            ManpowerGroup      27000
186                            Omnicom Group      74900
199                                  Aramark     216500
204                                     Visa      11300
221                         Waste Management      40600
248                                      ADP      55000
249                               First Data      24000
294                               MasterCard      11300
307                          PayPal Holdings      16800
312                        Republic Services      33000
355                        Interpublic Group      49200
392   Fidelity National Information Services      55000
404                    Alliance Data Systems      16000
440                           United Rentals      12700
467                           Kelly Services       8100
468                            Western Union      10000
481                               S&P Global      20400
485                           ABM Industries     120000
492                                   Fiserv      22000
503                Robert Half International      16100
545                                   Cintas      32000
626                            Towers Watson      16300
635                                      ADT      17100
652                                  Moody’s      10400
677                            Clean Harbors      12900
694                                   Vantiv       3313
714                                  Brink’s      59900
729                            Iron Mountain      20000
734              Service Corp. International      19720
735                               Stericycle      25472
737                          Graham Holdings      11585
744                                Convergys     130000
767                              DST Systems      13420
776                    Total System Services      10500
777                          Global Payments       4438
783                                  Paychex      13000
791                                 TrueBlue       5500
792           Broadridge Financial Solutions       7400
796                Heartland Payment Systems       4272
801                                  Equifax       8000
803                             TriNet Group       2500
816                                Insperity       2400
819            ServiceMaster Global Holdings      13000
820                   Apollo Education Group      23400
869                                     West      10630
870                           Public Storage       5300
886                               IHS Markit       8600
939                        Waste Connections       7227
951                            On Assignment       3320
952                         Verisk Analytics       7783
993                    DeVry Education Group      11770

                              Industry             Location  Profits  Revenue
Rank
144                     Temporary Help        Milwaukee, WI      419    19330
186             Advertising, marketing         New York, NY     1094    15134
199   Diversified Outsourcing Services     Philadelphia, PA      236    14329
204            Financial Data Services      Foster City, CA     6328    13880
221                   Waste Management          Houston, TX      753    12961
248   Diversified Outsourcing Services         Roseland, NJ     1453    11477
249            Financial Data Services          Atlanta, GA    -1481    11451
294            Financial Data Services         Purchase, NY     3808     9667
307            Financial Data Services         San Jose, CA     1228     9248
312                   Waste Management          Phoenix, AZ      750     9115
355             Advertising, marketing         New York, NY      455     7614
392            Financial Data Services     Jacksonville, FL      632     6595
404            Financial Data Services            Plano, TX      597     6440
440                      Miscellaneous         Stamford, CT      585     5817
467                     Temporary Help             Troy, MI       54     5518
468            Financial Data Services        Englewood, CO      838     5484
481            Financial Data Services         New York, NY     1156     5313
485   Diversified Outsourcing Services         New York, NY       76     5291
492            Financial Data Services       Brookfield, WI      712     5254
503                     Temporary Help       Menlo Park, CA      358     5095
545   Diversified Outsourcing Services       Cincinnati, OH      431     4508
626   Diversified Outsourcing Services        Arlington, VA      385     3645
635   Diversified Outsourcing Services       Boca Raton, FL      296     3574
652            Financial Data Services         New York, NY      941     3485
677                   Waste Management          Norwell, MA       44     3275
694            Financial Data Services  Symmes Township, OH      148     3160
714   Diversified Outsourcing Services         Richmond, VA      -12     3066
729   Diversified Outsourcing Services           Boston, MA      123     3008
734                      Miscellaneous          Houston, TX      234     2986
735                   Waste Management      Lake Forest, IL      267     2986
737                          Education        Arlington, VA     -101     2984
744   Diversified Outsourcing Services       Cincinnati, OH      169     2951
767            Financial Data Services      Kansas City, MO      358     2825
776            Financial Data Services         Columbus, GA      364     2780
777            Financial Data Services          Atlanta, GA      278     2774
783   Diversified Outsourcing Services        Rochester, NY      675     2740
791                     Temporary Help           Tacoma, WA       71     2696
792            Financial Data Services     Lake Success, NY      287     2694
796            Financial Data Services        Princeton, NJ       85     2682
801            Financial Data Services          Atlanta, GA      429     2664
803   Diversified Outsourcing Services      San Leandro, CA       32     2659
816   Diversified Outsourcing Services         Kingwood, TX       39     2604
819   Diversified Outsourcing Services          Memphis, TN      160     2594
820                          Education          Phoenix, AZ       30     2591
869   Diversified Outsourcing Services            Omaha, NE      242     2383
870                      Miscellaneous         Glendale, CA     1311     2382
886            Financial Data Services        Englewood, CO      240     2314
939                   Waste Management    The Woodlands, TX      -96     2117
951                     Temporary Help        Calabasas, CA       98     2077
952            Financial Data Services      Jersey City, NJ      508     2068
993                          Education    Downers Grove, IL      140     1910
Group: Chemicals                                  Company  Employees   Industry  \
Rank
56                          Dow Chemical      49495  Chemicals
101                               DuPont      52000  Chemicals
182                       PPG Industries      46600  Chemicals
189                             Monsanto      24000  Chemicals
206                               Ecolab      47145  Chemicals
253                     Sherwin-Williams      40706  Chemicals
262                              Praxair      26657  Chemicals
277                             Huntsman      15000  Chemicals
288             Air Products & Chemicals      19550  Chemicals
296                     Eastman Chemical      15000  Chemicals
316                               Mosaic       8900  Chemicals
538                    RPM International      12864  Chemicals
549                    Westlake Chemical       4225  Chemicals
555                              Valspar      11130  Chemicals
566               CF Industries Holdings       2850  Chemicals
580                               Hexion       5100  Chemicals
613                               Axiall       5830  Chemicals
624                            Albemarle       6963  Chemicals
654                                  FMC       6000  Chemicals
668                              PolyOne       6900  Chemicals
717                           W.R. Grace       6700  Chemicals
720   International Flavors & Fragrances       6732  Chemicals
724                   Scotts Miracle-Gro       7900  Chemicals
758                                Cabot       4600  Chemicals
761                                 Olin       6200  Chemicals
829          Platform Specialty Products       8200  Chemicals
865                          A. Schulman       5000  Chemicals
898                         MPM Holdings       5000  Chemicals
934                            NewMarket       1979  Chemicals
949                          H.B. Fuller       4425  Chemicals

                 Location  Profits  Revenue
Rank
56            Midland, MI     7685    48778
101        Wilmington, DE     1953    27940
182        Pittsburgh, PA     1406    15330
189         St. Louis, MO     2314    15001
206          St. Paul, MN     1002    13545
253         Cleveland, OH     1054    11339
262           Danbury, CT     1547    10776
277     The Woodlands, TX       93    10299
288         Allentown, PA     1278     9895
296         Kingsport, TN      848     9648
316          Plymouth, MN     1000     8895
538            Medina, OH      240     4595
549           Houston, TX      646     4463
555       Minneapolis, MN      400     4393
566         Deerfield, IL      700     4308
580          Columbus, OH      -40     4140
613           Atlanta, GA     -816     3787
624       Baton Rouge, LA      335     3651
654      Philadelphia, PA      489     3471
668         Avon Lake, OH      145     3378
717          Columbia, MD      144     3052
720          New York, NY      419     3023
724        Marysville, OH      160     3017
758            Boston, MA     -334     2871
761           Clayton, MO       -1     2854
829   West Palm Beach, FL     -309     2542
865          Fairlawn, OH       27     2392
898         Waterford, NY      -83     2289
934          Richmond, VA      239     2141
949          St. Paul, MN       87     2084
Group: Media                            Company  Employees              Industry  \
Rank
53                          Disney     185000         Entertainment
96        Twenty-First Century Fox      20500         Entertainment
99                     Time Warner      24800         Entertainment
203                            CBS      19080         Entertainment
213                         Viacom       9445         Entertainment
255          R.R. Donnelley & Sons      68400  Publishing, Printing
327                     News Corp.      25000  Publishing, Printing
366      Live Nation Entertainment      12200         Entertainment
406       Discovery Communications       7000         Entertainment

Group: Health Care                          Company  Employees  \
Rank
5                       McKesson      70400
6             UnitedHealth Group     200000
12             AmerisourceBergen      17000
21               Cardinal Health      34500
22       Express Scripts Holding      25900
33                        Anthem      53000
39             Johnson & Johnson     127100
46                         Aetna      50100
52                        Humana      50100
55                        Pfizer      97900
63                  HCA Holdings     203500
72                         Merck      68000
79                         Cigna      39300
86               Gilead Sciences       8000
123                       AbbVie      28000
124                      Centene      18200
125     Community Health Systems     123000
130                        Amgen      17900
138          Abbott Laboratories      74000
140             Tenet Healthcare     119148
141                    Eli Lilly      41275
168         Bristol-Myers Squibb      25000
172                   Health Net       8584
200   DaVita HealthCare Partners      60400
201            Molina Healthcare      21000
202        WellCare Health Plans       6900
263                       Biogen       7350
268                 Henry Schein      19000
278             Becton Dickinson      49517
286         Baxter International      49400
...                          ...        ...
515      Brookdale Senior Living      67500
527                       Zoetis       9000
537              Magellan Health       6900
553                       Cerner      22200
559                    Patterson       7000
583    Regeneron Pharmaceuticals       4300
618      Select Medical Holdings      34700
629         Team Health Holdings      18800
661                    C.R. Bard      15000
684                         NBTY      13100
693                  HealthSouth      27929
697             Iasis Healthcare      11950
708       Varian Medical Systems       7300
746          IMS Health Holdings      15000
749          Triple-S Management       3405
766                       AmSurg      10700
775                       Mednax       8645
790                      Hologic       5290
799              Dentsply Sirona      11400
815      Alexion Pharmaceuticals       2924
818                        Alere       9800
845         Edwards Lifesciences       9800
868           Intuitive Surgical       3211
881        Parexel International      18660
883              inVentiv Health      14000
935                          VCA      12700
960                   PharMerica       5200
965         Bio-Rad Laboratories       7770
977            Hill-Rom Holdings      10000
978           Providence Service       9072

                                      Industry               Location  \
Rank
5                     Wholesalers: Health Care      San Francisco, CA
6      Health Care: Insurance and Managed Care         Minnetonka, MN
12                    Wholesalers: Health Care       Chesterbrook, PA
21                    Wholesalers: Health Care             Dublin, OH
22    Health Care: Pharmacy and Other Services          St. Louis, MO
33     Health Care: Insurance and Managed Care       Indianapolis, IN
39                             Pharmaceuticals      New Brunswick, NJ
46     Health Care: Insurance and Managed Care           Hartford, CT
52     Health Care: Insurance and Managed Care         Louisville, KY
55                             Pharmaceuticals           New York, NY
63             Health Care: Medical Facilities          Nashville, TN
72                             Pharmaceuticals         Kenilworth, NJ
79     Health Care: Insurance and Managed Care         Bloomfield, CT
86                             Pharmaceuticals        Foster City, CA
123                            Pharmaceuticals      North Chicago, IL
124    Health Care: Insurance and Managed Care          St. Louis, MO
125            Health Care: Medical Facilities           Franklin, TN
130                            Pharmaceuticals      Thousand Oaks, CA
138             Medical Products and Equipment        Abbott Park, IL
140            Health Care: Medical Facilities             Dallas, TX
141                            Pharmaceuticals       Indianapolis, IN
168                            Pharmaceuticals           New York, NY
172    Health Care: Insurance and Managed Care     Woodland Hills, CA
200            Health Care: Medical Facilities             Denver, CO
201    Health Care: Insurance and Managed Care         Long Beach, CA
202    Health Care: Insurance and Managed Care              Tampa, FL
263                            Pharmaceuticals          Cambridge, MA
268                   Wholesalers: Health Care           Melville, NY
278             Medical Products and Equipment     Franklin Lakes, NJ
286             Medical Products and Equipment          Deerfield, IL
...                                        ...                    ...
515            Health Care: Medical Facilities          Brentwood, TN
527                            Pharmaceuticals       Florham Park, NJ
537    Health Care: Insurance and Managed Care         Scottsdale, AZ
553   Health Care: Pharmacy and Other Services  North Kansas City, MO
559                   Wholesalers: Health Care           St. Paul, MN
583                            Pharmaceuticals          Tarrytown, NY
618            Health Care: Medical Facilities      Mechanicsburg, PA
629   Health Care: Pharmacy and Other Services          Knoxville, TN
661             Medical Products and Equipment        Murray Hill, NJ
684                            Pharmaceuticals         Ronkonkoma, NY
693            Health Care: Medical Facilities         Birmingham, AL
697            Health Care: Medical Facilities           Franklin, TN
708             Medical Products and Equipment          Palo Alto, CA
746   Health Care: Pharmacy and Other Services            Danbury, CT
749    Health Care: Insurance and Managed Care           San Juan, PR
766            Health Care: Medical Facilities          Nashville, TN
775   Health Care: Pharmacy and Other Services            Sunrise, FL
790             Medical Products and Equipment        Marlborough, MA
799             Medical Products and Equipment               York, PA
815                            Pharmaceuticals          New Haven, CT
818             Medical Products and Equipment            Waltham, MA
845             Medical Products and Equipment             Irvine, CA
868             Medical Products and Equipment          Sunnyvale, CA
881   Health Care: Pharmacy and Other Services            Waltham, MA
883   Health Care: Pharmacy and Other Services         Burlington, MA
935            Health Care: Medical Facilities        Los Angeles, CA
960   Health Care: Pharmacy and Other Services         Louisville, KY
965             Medical Products and Equipment           Hercules, CA
977             Medical Products and Equipment            Chicago, IL
978   Health Care: Pharmacy and Other Services             Tucson, AZ

      Profits  Revenue
Rank
5        1476   181241
6        5813   157107
12       -135   135962
21       1215   102531
22       2476   101752
33       2560    79157
39      15409    70074
46       2390    60337
52       1276    54289
55       6960    48851
63       2129    43591
72       4442    39498
79       2094    37876
86      18108    32639
123      5144    22859
124       355    22795
125       158    22678
130      6939    21662
138      4423    20661
140      -140    20111
141      2408    19959
168      1565    16560
172       186    16244
200       270    14210
201       143    14178
202       119    13890
263      3547    10764
268       479    10630
278       695    10282
286       968     9968
...       ...      ...
515      -458     4961
527       339     4765
537        31     4597
553       539     4425
559       223     4375
583       636     4104
618       131     3743
629        83     3597
661       135     3416
684        74     3226
693       183     3163
697        -8     3158
708       412     3099
746       417     2921
749        52     2903
766       163     2833
775       336     2780
790       132     2705
799       251     2674
815       144     2604
818       346     2601
845       495     2494
868       589     2384
881       148     2330
883      -152     2321
935       211     2134
960        35     2029
965       113     2019
977        48     1988
978        84     1987

[75 rows x 6 columns]
Group: Materials                          Company  Employees                   Industry  \
Rank
126                        Alcoa      60000                     Metals
127          International Paper      56000      Packaging, Containers
170                        Nucor      23700                     Metals
244          United States Steel      33200                     Metals
251                     WestRock      41400      Packaging, Containers
303    Reliance Steel & Aluminum      13400                     Metals
321               Crown Holdings      24000      Packaging, Containers
341                         Ball      15200      Packaging, Containers
356               Steel Dynamics       7500                     Metals
373                 Weyerhaeuser      12600  Forest and Paper Products
375                   Sealed Air      23000      Packaging, Containers
383             AK Steel Holding       8500                     Metals
417            Commercial Metals       9126                     Metals
418               Owens-Illinois      27000      Packaging, Containers
426       A-Mark Precious Metals         52              Miscellaneous
435               Avery Dennison      25000      Packaging, Containers
446   Packaging Corp. of America      13000      Packaging, Containers
480                Owens Corning      15000  Building Materials, Glass
489                       Domtar       9850  Forest and Paper Products
514              Sonoco Products      21000      Packaging, Containers
518         Berry Plastics Group      16000      Packaging, Containers
577    Graphic Packaging Holding      12000      Packaging, Containers
586                        Bemis      17696      Packaging, Containers
616                          USG       8900  Building Materials, Glass
617              Silgan Holdings       9600      Packaging, Containers
620       Allegheny Technologies       9200                     Metals
625     Resolute Forest Products       8000  Forest and Paper Products
628                        Greif      13150      Packaging, Containers
637         Builders FirstSource      14000  Building Materials, Glass
639                     Carlisle      12000  Building Materials, Glass
641    Martin Marietta Materials       7299  Building Materials, Glass
660             Vulcan Materials       7187  Building Materials, Glass
667       Worthington Industries      10500                     Metals
687                       Aleris       5200                     Metals
691              Ryerson Holding       3600                     Metals
751    Universal Forest Products       7000  Forest and Paper Products
774   KapStone Paper & Packaging       6400      Packaging, Containers
793                        Verso       1630  Forest and Paper Products
857   Armstrong World Industries       7600  Building Materials, Glass
885                   AptarGroup      13000      Packaging, Containers
911         Carpenter Technology       4900                     Metals
982             Century Aluminum       1778                     Metals
986   Schnitzer Steel Industries       2955                     Metals

              Location  Profits  Revenue
Rank
126       New York, NY     -322    22534
127        Memphis, TN      938    22365
170      Charlotte, NC      358    16439
244     Pittsburgh, PA    -1642    11574
251       Richmond, VA      507    11381
303    Los Angeles, CA      312     9351
321   Philadelphia, PA      393     8762
341     Broomfield, CO      281     7997
356     Fort Wayne, IN     -130     7594
373    Federal Way, WA      506     7082
375      Charlotte, NC      335     7032
383   West Chester, OH     -509     6693
417         Irving, TX      142     6162
418     Perrysburg, OH      -74     6156
426   Santa Monica, CA        7     6070
435       Glendale, CA      274     5967
446    Lake Forest, IL      437     5742
480         Toledo, OH      330     5350
489      Fort Mill, SC      142     5264
514     Hartsville, SC      250     4964
518     Evansville, IN       86     4881
577        Atlanta, GA      230     4160
586         Neenah, WI      239     4071
616        Chicago, IL      991     3776
617       Stamford, CT      172     3764
620     Pittsburgh, PA     -378     3720
625        Catawba, SC     -257     3645
628       Delaware, OH       72     3617
637         Dallas, TX      -23     3564
639      Charlotte, NC      320     3543
641        Raleigh, NC      289     3540
660     Birmingham, AL      221     3422
667       Columbus, OH       77     3384
687      Cleveland, OH       49     3206
691        Chicago, IL       -1     3167
751   Grand Rapids, MI       81     2887
774     Northbrook, IL      106     2789
793        Memphis, TN     -477     2692
857      Lancaster, PA       94     2420
885   Crystal Lake, IL      199     2317
911     Wyomissing, PA       59     2227
982        Chicago, IL      -59     1950
986       Portland, OR     -197     1924
Group: Aerospace & Defense                             Company  Employees               Industry  \
Rank
24                           Boeing     161400  Aerospace and Defense
45              United Technologies     197200  Aerospace and Defense
60                  Lockheed Martin     126000  Aerospace and Defense
88                 General Dynamics      99900  Aerospace and Defense
118                Northrop Grumman      65000  Aerospace and Defense
120                        Raytheon      61000  Aerospace and Defense
209                         Textron      35000  Aerospace and Defense
245              L-3 Communications      38000  Aerospace and Defense
282             Precision Castparts      30106  Aerospace and Defense
378   Huntington Ingalls Industries      35995  Aerospace and Defense
389     Spirit AeroSystems Holdings      15200  Aerospace and Defense
490                Rockwell Collins      19500  Aerospace and Defense
560                     Orbital ATK      12300  Aerospace and Defense
605                   Triumph Group      15153  Aerospace and Defense
785                   B/E Aerospace      10057  Aerospace and Defense
788                 TransDigm Group       8200  Aerospace and Defense
836                            Moog      10691  Aerospace and Defense
903                  Curtiss-Wright       8400  Aerospace and Defense
958                        Woodward       6955  Aerospace and Defense
987           Delta Tucker Holdings      12000  Aerospace and Defense

              Location  Profits  Revenue
Rank
24         Chicago, IL     5176    96114
45      Farmington, CT     7608    61047
60        Bethesda, MD     3605    46132
88    Falls Church, VA     2965    31469
118   Falls Church, VA     1990    23526
120        Waltham, MA     2074    23247
209     Providence, RI      697    13423
245       New York, NY     -240    11554
282       Portland, OR     1530    10056
378   Newport News, VA      404     7020
389        Wichita, KS      789     6644
490   Cedar Rapids, IA      686     5262
560         Dulles, VA      159     4369
605         Berwyn, PA      239     3889
785     Wellington, FL      286     2730
788      Cleveland, OH      447     2707
836           Elma, NY      132     2526
903      Charlotte, NC      146     2264
958   Fort Collins, CO      182     2038
987         McLean, VA     -133     1923
Group: Apparel                    Company  Employees Industry             Location  Profits  \
Rank
91                    Nike      62600  Apparel        Beaverton, OR     3273
231                     VF      64000  Apparel       Greensboro, NC     1232
340                    PVH      26200  Apparel         New York, NY      572
354           Ralph Lauren      20000  Apparel         New York, NY      702
448            Hanesbrands      65300  Apparel    Winston-Salem, NC      429
547           Levi Strauss      12500  Apparel    San Francisco, CA      209
575                  Coach      12950  Apparel         New York, NY      402
597           Under Armour       9600  Apparel        Baltimore, MD      233
683           Fossil Group      15100  Apparel       Richardson, TX      221
695        Skechers U.S.A.       6400  Apparel  Manhattan Beach, CA      232
726               Carter’s      16800  Apparel          Atlanta, GA      238
794   Wolverine World Wide       6550  Apparel         Rockford, MI      123
877    G-III Apparel Group       8919  Apparel         New York, NY      114
882    Columbia Sportswear       5978  Apparel         Portland, OR      174
917                  Guess      13500  Apparel      Los Angeles, CA       82

      Revenue
Rank
91      30601
231     12377
340      8020
354      7620
448      5732
547      4495
575      4192
597      3963
683      3229
695      3159
726      3014
794      2692
877      2344
882      2326
917      2204
Group: Motor Vehicles & Parts                             Company  Employees                  Industry  \
Rank
8                    General Motors     215000  Motor Vehicles and Parts
9                        Ford Motor     199000  Motor Vehicles and Parts
70                 Johnson Controls     139000  Motor Vehicles and Parts
147                          Paccar      23000  Motor Vehicles and Parts
154                            Lear     136200  Motor Vehicles and Parts
169          Goodyear Tire & Rubber      66000  Motor Vehicles and Parts
281          Navistar International      13800  Motor Vehicles and Parts
310                         Autoliv      59350  Motor Vehicles and Parts
334                         Tenneco      30000  Motor Vehicles and Parts
339                      BorgWarner      30000  Motor Vehicles and Parts
424                         Oshkosh      13300  Motor Vehicles and Parts
428                    Dana Holding      23100  Motor Vehicles and Parts
470                         Visteon      11000  Motor Vehicles and Parts
588                    Tesla Motors      13058  Motor Vehicles and Parts
591                 Thor Industries      10450  Motor Vehicles and Parts
604   American Axle & Manufacturing      13054  Motor Vehicles and Parts
647                         Meritor       8400  Motor Vehicles and Parts
670        Cooper-Standard Holdings      29000  Motor Vehicles and Parts
718     Metaldyne Performance Group      12000  Motor Vehicles and Parts
739            Cooper Tire & Rubber       9119  Motor Vehicles and Parts
811                  WABCO Holdings      12429  Motor Vehicles and Parts
957             Tower International       8300  Motor Vehicles and Parts
961                 Wabash National       5300  Motor Vehicles and Parts
979   Allison Transmission Holdings       2700  Motor Vehicles and Parts

                    Location  Profits  Revenue
Rank
8                Detroit, MI     9687   152356
9               Dearborn, MI     7373   149558
70             Milwaukee, WI     1563    40204
147             Bellevue, WA     1604    19115
154           Southfield, MI      746    18211
169                Akron, OH      307    16443
281                Lisle, IL     -184    10140
310         Auburn Hills, MI      457     9170
334          Lake Forest, IL      247     8209
339         Auburn Hills, MI      610     8023
424              Oshkosh, WI      230     6098
428               Maumee, OH      159     6060
470   Van Buren Township, MI     2284     5444
588            Palo Alto, CA     -889     4046
591              Elkhart, IN      199     4007

In [56]:
# Get Company in alphabetical order (first and last)
sectors.max() 
sectors.min()
sectors.sum() # only numbers --> sectors.get_group('Apparel')['Revenue'].sum()
sectors.mean()

                                   Revenue      Profits     Employees
Sector
Aerospace & Defense           17897.000000  1437.100000  48402.850000
Apparel                        6397.866667   549.066667  23093.133333
Business Services              5337.156863   553.470588  26687.254902
Chemicals                      8129.900000   754.266667  15455.033333
Energy                        12441.057377  -602.024590   9745.303279
Engineering & Construction     5922.423077   204.000000  15642.615385
Financials                    15950.784173  1872.007194  24172.287770
Food and Drug Stores          32251.266667  1117.266667  93026.533333
Food, Beverages & Tobacco     12929.465116  1195.744186  28177.488372
Health Care                   21529.426667  1414.853333  35710.520000
Hotels, Resturants & Leisure   6781.840000   827.880000  99369.800000
Household Products             8383.464286   515.285714  23072.785714
Industrials                   10816.978261   451.391304  33591.934783
Materials                      6026.627907   102.976744  14840.069767
Media                          8830.560000   973.880000  22012.560000
Motor Vehicles & Parts        20105.833333  1079.083333  45106.666667
Retailing                     18313.450000   597.875000  77845.362500
Technology                    13505.882353  1769.343137  35087.735294
Telecommunications            30788.933333  3242.466667  55497.866667
Transportation                11347.444444  1226.916667  42688.694444
Wholesalers                   11120.000000   205.825000  13139.925000

In [58]:
# Series --> Sum for each sector of all the revenues
sectors['Revenue'].sum()

Sector
Aerospace & Defense              357940
Apparel                           95968
Business Services                272195
Chemicals                        243897
Energy                          1517809
Engineering & Construction       153983
Financials                      2217159
Food and Drug Stores             483769
Food, Beverages & Tobacco        555967
Health Care                     1614707
Hotels, Resturants & Leisure     169546
Household Products               234737
Industrials                      497581
Materials                        259145
Media                            220764
Motor Vehicles & Parts           482540
Retailing                       1465076
Technology                      1377600
Telecommunications               461834
Transportation                   408508
Wholesalers                      444800
Name: Revenue, dtype: int64

In [63]:
sectors['Revenue'].max() # max, min, mean

Sector
Aerospace & Defense              96114
Apparel                          30601
Business Services                19330
Chemicals                        48778
Energy                          246204
Engineering & Construction       18114
Financials                      210821
Food and Drug Stores            153290
Food, Beverages & Tobacco        67702
Health Care                     181241
Hotels, Resturants & Leisure     25413
Household Products               78756
Industrials                     140389
Materials                        22534
Media                            52465
Motor Vehicles & Parts          152356
Retailing                       482130
Technology                      233715
Telecommunications              146801
Transportation                   58363
Wholesalers                      48681
Name: Revenue, dtype: int64

In [64]:
sectors[['Revenue', 'Employees']].sum()

                              Revenue  Employees
Sector
Aerospace & Defense            357940     968057
Apparel                         95968     346397
Business Services              272195    1361050
Chemicals                      243897     463651
Energy                        1517809    1188927
Engineering & Construction     153983     406708
Financials                    2217159    3359948
Food and Drug Stores           483769    1395398
Food, Beverages & Tobacco      555967    1211632
Health Care                   1614707    2678289
Hotels, Resturants & Leisure   169546    2484245
Household Products             234737     646038
Industrials                    497581    1545229
Materials                      259145     638123
Media                          220764     550314
Motor Vehicles & Parts         482540    1082560
Retailing                     1465076    6227629
Technology                    1377600    3578949
Telecommunications             461834     832468
Transportation                 408508    1536793
Wholesalers                    444800     525597

## Group By with multiple Columns

In [66]:
sectors = data.groupby(['Sector', 'Industry'])

In [69]:
# Double Index
sectors.size()

Sector                      Industry
Aerospace & Defense         Aerospace and Defense                             20
Apparel                     Apparel                                           15
Business Services           Advertising, marketing                             2
                            Diversified Outsourcing Services                  14
                            Education                                          3
                            Financial Data Services                           19
                            Miscellaneous                                      3
                            Temporary Help                                     5
                            Waste Management                                   5
Chemicals                   Chemicals                                         30
Energy                      Energy                                            14
                            Mining, Crude-Oil Production                      28
                            Miscellaneous                                      1
                            Oil and Gas Equipment, Services                    9
                            Petroleum Refining                                17
                            Pipelines                                         12
                            Utilities: Gas and Electric                       41
Engineering & Construction  Engineering, Construction                         14
                            Homebuilders                                      12
Financials                  Commercial Banks                                  28
                            Diversified Financials                            15
                            Insurance: Life, Health (Mutual)                  10
                            Insurance: Life, Health (stock)                   18
                            Insurance: Property and Casualty (Mutual)          7
                            Insurance: Property and Casualty (Stock)          28
                            Real estate                                       15
                            Securities                                        18
Food and Drug Stores        Food and Drug Stores                              15
Food, Beverages & Tobacco   Beverages                                          9
                            Food Consumer Products                            20
                                                                              ..
Materials                   Metals                                            14
                            Miscellaneous                                      1
                            Packaging, Containers                             16
Media                       Entertainment                                     18
                            Publishing, Printing                               7
Motor Vehicles & Parts      Motor Vehicles and Parts                          24
Retailing                   Automotive Retailing, Services                    10
                            General Merchandisers                             10
                            Specialty Retailers: Apparel                      18
                            Specialty Retailers: Other                        42
Technology                  Computer Peripherals                               4
                            Computer Software                                 14
                            Computers, Office Equipment                        7
                            Information Technology Services                   13
                            Internet Services and Retailing                   15
                            Network and Other Communications Equipment        14
                            Scientific,Photographic and Control Equipment     12
                            Semiconductors and Other Electronic Components    23
Telecommunications          Telecommunications                                15
Transportation              Airlines                                           9
                            Mail, Package, and Freight Delivery                2
                            Miscellaneous                                      1
                            Railroads                                          5
                            Transportation Equipment                           5
                            Transportation and Logistics                       5
                            Trucking, Truck Leasing                            9
Wholesalers                 Miscellaneous                                      1
                            Wholesalers: Diversified                          25
                            Wholesalers: Electronics and Office Equipment      8
                            Wholesalers: Food and Grocery                      6
Length: 79, dtype: int64

In [71]:
sectors.sum() # --> MultiIndex DataFrame

                                                                           Revenue  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            357940
Apparel                    Apparel                                           95968
Business Services          Advertising, marketing                            22748
                           Diversified Outsourcing Services                  64829
                           Education                                          7485
                           Financial Data Services                          100778
                           Miscellaneous                                     11185
                           Temporary Help                                    34716
                           Waste Management                                  30454
Chemicals                  Chemicals                                        243897
Energy                     Energy                                            67749
                           Mining, Crude-Oil Production                     176435
                           Miscellaneous                                      3159
                           Oil and Gas Equipment, Services                   82827
                           Petroleum Refining                               705472
                           Pipelines                                        138756
                           Utilities: Gas and Electric                      343411
Engineering & Construction Engineering, Construction                         99774
                           Homebuilders                                      54209
Financials                 Commercial Banks                                 623669
                           Diversified Financials                           327075
                           Insurance: Life, Health (Mutual)                 181336
                           Insurance: Life, Health (stock)                  245551
                           Insurance: Property and Casualty (Mutual)        143682
                           Insurance: Property and Casualty (Stock)         548027
                           Real estate                                       62748
                           Securities                                        85071
Food and Drug Stores       Food and Drug Stores                             483769
Food, Beverages & Tobacco  Beverages                                         79396
                           Food Consumer Products                           238954
...                                                                            ...
Materials                  Metals                                            99925
                           Miscellaneous                                      6070
                           Packaging, Containers                            105965
Media                      Entertainment                                    186276
                           Publishing, Printing                              34488
Motor Vehicles & Parts     Motor Vehicles and Parts                         482540
Retailing                  Automotive Retailing, Services                   113823
                           General Merchandisers                            684320
                           Specialty Retailers: Apparel                     122975
                           Specialty Retailers: Other                       543958
Technology                 Computer Peripherals                              48950
                           Computer Software                                179112
                           Computers, Office Equipment                      353781
                           Information Technology Services                  166067
                           Internet Services and Retailing                  259136
                           Network and Other Communications Equipment       125697
                           Scientific,Photographic and Control Equipment     65832
                           Semiconductors and Other Electronic Components   179025
Telecommunications         Telecommunications                               461834
Transportation             Airlines                                         158948
                           Mail, Package, and Freight Delivery              105816
                           Miscellaneous                                      2148
                           Railroads                                         48554
                           Transportation Equipment                          23855
                           Transportation and Logistics                      33237
                           Trucking, Truck Leasing                           35950
Wholesalers                Miscellaneous                                      8982
                           Wholesalers: Diversified                         176138
                           Wholesalers: Electronics and Office Equipment    147906
                           Wholesalers: Food and Grocery                    111774

                                                                           Profits  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                             28742
Apparel                    Apparel                                            8236
Business Services          Advertising, marketing                             1549
                           Diversified Outsourcing Services                   4305
                           Education                                            69
                           Financial Data Services                           17456
                           Miscellaneous                                      2130
                           Temporary Help                                     1000
                           Waste Management                                   1718
Chemicals                  Chemicals                                         22628
Energy                     Energy                                           -13038
                           Mining, Crude-Oil Production                    -124555
                           Miscellaneous                                       476
                           Oil and Gas Equipment, Services                   -4047
                           Petroleum Refining                                31888
                           Pipelines                                          5814
                           Utilities: Gas and Electric                       30015
Engineering & Construction Engineering, Construction                          1765
                           Homebuilders                                       3539
Financials                 Commercial Banks                                 129760
                           Diversified Financials                            28548
                           Insurance: Life, Health (Mutual)                   5601
                           Insurance: Life, Health (stock)                   19731
                           Insurance: Property and Casualty (Mutual)          8031
                           Insurance: Property and Casualty (Stock)          44803
                           Real estate                                        9480
                           Securities                                        14255
Food and Drug Stores       Food and Drug Stores                              16759
Food, Beverages & Tobacco  Beverages                                         11698
                           Food Consumer Products                            19263
...                                                                            ...
Materials                  Metals                                            -2241
                           Miscellaneous                                         7
                           Packaging, Containers                              4445
Media                      Entertainment                                     25686
                           Publishing, Printing                              -1339
Motor Vehicles & Parts     Motor Vehicles and Parts                          25898
Retailing                  Automotive Retailing, Services                     2550
                           General Merchandisers                             20137
                           Specialty Retailers: Apparel                       4583
                           Specialty Retailers: Other                        20560
Technology                 Computer Peripherals                               3975
                           Computer Software                                 26457
                           Computers, Office Equipment                       58433
                           Information Technology Services                   16402
                           Internet Services and Retailing                   22232
                           Network and Other Communications Equipment        18907
                           Scientific,Photographic and Control Equipment      9346
                           Semiconductors and Other Electronic Components    24721
Telecommunications         Telecommunications                                48637
Transportation             Airlines                                          23800
                           Mail, Package, and Freight Delivery                5894
                           Miscellaneous                                       227
                           Railroads                                          9005
                           Transportation Equipment                           2438
                           Transportation and Logistics                        895
                           Trucking, Truck Leasing                            1910
Wholesalers                Miscellaneous                                        17
                           Wholesalers: Diversified                           5193
                           Wholesalers: Electronics and Office Equipment      1857
                           Wholesalers: Food and Grocery                      1166

                                                                           Employees
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                              968057
Apparel                    Apparel                                            346397
Business Services          Advertising, marketing                             124100
                           Diversified Outsourcing Services                   708330
                           Education                                           46755
                           Financial Data Services                            264926
                           Miscellaneous                                       37720
                           Temporary Help                                      60020
                           Waste Management                                   119199
Chemicals                  Chemicals                                          463651
Energy                     Energy                                              70072
                           Mining, Crude-Oil Production                       149110
                           Miscellaneous                                        6700
                           Oil and Gas Equipment, Services                    225795
                           Petroleum Refining                                 244880
                           Pipelines                                           72141
                           Utilities: Gas and Electric                        420229
Engineering & Construction Engineering, Construction                          368104
                           Homebuilders                                        38604
Financials                 Commercial Banks                                  1539024
                           Diversified Financials                             329114
                           Insurance: Life, Health (Mutual)                    58801
                           Insurance: Life, Health (stock)                    202233
                           Insurance: Property and Casualty (Mutual)          133148
                           Insurance: Property and Casualty (Stock)           794123
                           Real estate                                        160579
                           Securities                                         142926
Food and Drug Stores       Food and Drug Stores                              1395398
Food, Beverages & Tobacco  Beverages                                          199107
                           Food Consumer Products                             665439
...                                                                              ...
Materials                  Metals                                             193559
                           Miscellaneous                                          52
                           Packaging, Containers                              333446
Media                      Entertainment                                      383564
                           Publishing, Printing                               166750
Motor Vehicles & Parts     Motor Vehicles and Parts                          1082560
Retailing                  Automotive Retailing, Services                     174974
                           General Merchandisers                             3408100
                           Specialty Retailers: Apparel                       770543
                           Specialty Retailers: Other                        1874012
Technology                 Computer Peripherals                               175259
                           Computer Software                                  388796
                           Computers, Office Equipment                        468085
                           Information Technology Services                    985639
                           Internet Services and Retailing                    430855
                           Network and Other Communications Equipment         299310
                           Scientific,Photographic and Control Equipment      231501
                           Semiconductors and Other Electronic Components     599504
Telecommunications         Telecommunications                                 832468
Transportation             Airlines                                           391601
                           Mail, Package, and Freight Delivery                664275
                           Miscellaneous                                        4200
                           Railroads                                          121844
                           Transportation Equipment                            59726
                           Transportation and Logistics                       124691
                           Trucking, Truck Leasing                            170456
Wholesalers                Miscellaneous                                        9200
                           Wholesalers: Diversified                           233831
                           Wholesalers: Electronics and Office Equipment      166661
                           Wholesalers: Food and Grocery                      115905

[79 rows x 3 columns]

In [72]:
sectors['Revenue'].sum()

Sector                      Industry
Aerospace & Defense         Aerospace and Defense                             357940
Apparel                     Apparel                                            95968
Business Services           Advertising, marketing                             22748
                            Diversified Outsourcing Services                   64829
                            Education                                           7485
                            Financial Data Services                           100778
                            Miscellaneous                                      11185
                            Temporary Help                                     34716
                            Waste Management                                   30454
Chemicals                   Chemicals                                         243897
Energy                      Energy                                             67749
                            Mining, Crude-Oil Production                      176435
                            Miscellaneous                                       3159
                            Oil and Gas Equipment, Services                    82827
                            Petroleum Refining                                705472
                            Pipelines                                         138756
                            Utilities: Gas and Electric                       343411
Engineering & Construction  Engineering, Construction                          99774
                            Homebuilders                                       54209
Financials                  Commercial Banks                                  623669
                            Diversified Financials                            327075
                            Insurance: Life, Health (Mutual)                  181336
                            Insurance: Life, Health (stock)                   245551
                            Insurance: Property and Casualty (Mutual)         143682
                            Insurance: Property and Casualty (Stock)          548027
                            Real estate                                        62748
                            Securities                                         85071
Food and Drug Stores        Food and Drug Stores                              483769
Food, Beverages & Tobacco   Beverages                                          79396
                            Food Consumer Products                            238954
                                                                               ...
Materials                   Metals                                             99925
                            Miscellaneous                                       6070
                            Packaging, Containers                             105965
Media                       Entertainment                                     186276
                            Publishing, Printing                               34488
Motor Vehicles & Parts      Motor Vehicles and Parts                          482540
Retailing                   Automotive Retailing, Services                    113823
                            General Merchandisers                             684320
                            Specialty Retailers: Apparel                      122975
                            Specialty Retailers: Other                        543958
Technology                  Computer Peripherals                               48950
                            Computer Software                                 179112
                            Computers, Office Equipment                       353781
                            Information Technology Services                   166067
                            Internet Services and Retailing                   259136
                            Network and Other Communications Equipment        125697
                            Scientific,Photographic and Control Equipment      65832
                            Semiconductors and Other Electronic Components    179025
Telecommunications          Telecommunications                                461834
Transportation              Airlines                                          158948
                            Mail, Package, and Freight Delivery               105816
                            Miscellaneous                                       2148
                            Railroads                                          48554
                            Transportation Equipment                           23855
                            Transportation and Logistics                       33237
                            Trucking, Truck Leasing                            35950
Wholesalers                 Miscellaneous                                       8982
                            Wholesalers: Diversified                          176138
                            Wholesalers: Electronics and Office Equipment     147906
                            Wholesalers: Food and Grocery                     111774
Name: Revenue, Length: 79, dtype: int64

## Aggregation Method

In [74]:
sectors = data.groupby('Sector')

In [78]:
# On selected column apply function
sectors.agg({'Revenue': 'sum', 
             'Profits': 'sum',
             'Employees': 'mean'
            })

                                 Employees  Profits  Revenue
Sector
Aerospace & Defense           48402.850000    28742   357940
Apparel                       23093.133333     8236    95968
Business Services             26687.254902    28227   272195
Chemicals                     15455.033333    22628   243897
Energy                         9745.303279   -73447  1517809
Engineering & Construction    15642.615385     5304   153983
Financials                    24172.287770   260209  2217159
Food and Drug Stores          93026.533333    16759   483769
Food, Beverages & Tobacco     28177.488372    51417   555967
Health Care                   35710.520000   106114  1614707
Hotels, Resturants & Leisure  99369.800000    20697   169546
Household Products            23072.785714    14428   234737
Industrials                   33591.934783    20764   497581
Materials                     14840.069767     4428   259145
Media                         22012.560000    24347   220764
Motor Vehicles & Parts        45106.666667    25898   482540
Retailing                     77845.362500    47830  1465076
Technology                    35087.735294   180473  1377600
Telecommunications            55497.866667    48637   461834
Transportation                42688.694444    44169   408508
Wholesalers                   13139.925000     8233   444800

In [82]:
# For each columns apply all
sectors.agg(['size', 'sum', 'mean'])

                             Revenue                        Profits          \
                                size      sum          mean    size     sum
Sector
Aerospace & Defense               20   357940  17897.000000      20   28742
Apparel                           15    95968   6397.866667      15    8236
Business Services                 51   272195   5337.156863      51   28227
Chemicals                         30   243897   8129.900000      30   22628
Energy                           122  1517809  12441.057377     122  -73447
Engineering & Construction        26   153983   5922.423077      26    5304
Financials                       139  2217159  15950.784173     139  260209
Food and Drug Stores              15   483769  32251.266667      15   16759
Food, Beverages & Tobacco         43   555967  12929.465116      43   51417
Health Care                       75  1614707  21529.426667      75  106114
Hotels, Resturants & Leisure      25   169546   6781.840000      25   20697
Household Products                28   234737   8383.464286      28   14428
Industrials                       46   497581  10816.978261      46   20764
Materials                         43   259145   6026.627907      43    4428
Media                             25   220764   8830.560000      25   24347
Motor Vehicles & Parts            24   482540  20105.833333      24   25898
Retailing                         80  1465076  18313.450000      80   47830
Technology                       102  1377600  13505.882353     102  180473
Telecommunications                15   461834  30788.933333      15   48637
Transportation                    36   408508  11347.444444      36   44169
Wholesalers                       40   444800  11120.000000      40    8233

                                          Employees
                                     mean      size      sum          mean
Sector
Aerospace & Defense           1437.100000        20   968057  48402.850000
Apparel                        549.066667        15   346397  23093.133333
Business Services              553.470588        51  1361050  26687.254902
Chemicals                      754.266667        30   463651  15455.033333
Energy                        -602.024590       122  1188927   9745.303279
Engineering & Construction     204.000000        26   406708  15642.615385
Financials                    1872.007194       139  3359948  24172.287770
Food and Drug Stores          1117.266667        15  1395398  93026.533333
Food, Beverages & Tobacco     1195.744186        43  1211632  28177.488372
Health Care                   1414.853333        75  2678289  35710.520000
Hotels, Resturants & Leisure   827.880000        25  2484245  99369.800000
Household Products             515.285714        28   646038  23072.785714
Industrials                    451.391304        46  1545229  33591.934783
Materials                      102.976744        43   638123  14840.069767
Media                          973.880000        25   550314  22012.560000
Motor Vehicles & Parts        1079.083333        24  1082560  45106.666667
Retailing                      597.875000        80  6227629  77845.362500
Technology                    1769.343137       102  3578949  35087.735294
Telecommunications            3242.466667        15   832468  55497.866667
Transportation                1226.916667        36  1536793  42688.694444
Wholesalers                    205.825000        40   525597  13139.925000

In [83]:
# Mixing
# On selected column apply function
sectors.agg({'Revenue': ['sum', 'mean'],
             'Profits': 'sum',
             'Employees': 'mean'
            })

                                 Employees Profits  Revenue
                                      mean     sum      sum          mean
Sector
Aerospace & Defense           48402.850000   28742   357940  17897.000000
Apparel                       23093.133333    8236    95968   6397.866667
Business Services             26687.254902   28227   272195   5337.156863
Chemicals                     15455.033333   22628   243897   8129.900000
Energy                         9745.303279  -73447  1517809  12441.057377
Engineering & Construction    15642.615385    5304   153983   5922.423077
Financials                    24172.287770  260209  2217159  15950.784173
Food and Drug Stores          93026.533333   16759   483769  32251.266667
Food, Beverages & Tobacco     28177.488372   51417   555967  12929.465116
Health Care                   35710.520000  106114  1614707  21529.426667
Hotels, Resturants & Leisure  99369.800000   20697   169546   6781.840000
Household Products            23072.785714   14428   234737   8383.464286
Industrials                   33591.934783   20764   497581  10816.978261
Materials                     14840.069767    4428   259145   6026.627907
Media                         22012.560000   24347   220764   8830.560000
Motor Vehicles & Parts        45106.666667   25898   482540  20105.833333
Retailing                     77845.362500   47830  1465076  18313.450000
Technology                    35087.735294  180473  1377600  13505.882353
Telecommunications            55497.866667   48637   461834  30788.933333
Transportation                42688.694444   44169   408508  11347.444444
Wholesalers                   13139.925000    8233   444800  11120.000000

In [84]:
aggregated = sectors.agg({'Revenue': ['sum', 'mean'],
             'Profits': 'sum',
             'Employees': 'mean'
            })

In [97]:
aggregated.loc['Apparel']

Employees  mean    23093.133333
Profits    sum      8236.000000
Revenue    sum     95968.000000
           mean     6397.866667
Name: Apparel, dtype: float64

In [93]:
aggregated['Revenue']['sum']

Sector
Aerospace & Defense              357940
Apparel                           95968
Business Services                272195
Chemicals                        243897
Energy                          1517809
Engineering & Construction       153983
Financials                      2217159
Food and Drug Stores             483769
Food, Beverages & Tobacco        555967
Health Care                     1614707
Hotels, Resturants & Leisure     169546
Household Products               234737
Industrials                      497581
Materials                        259145
Media                            220764
Motor Vehicles & Parts           482540
Retailing                       1465076
Technology                      1377600
Telecommunications               461834
Transportation                   408508
Wholesalers                      444800
Name: sum, dtype: int64

## Iteration through Groups

In [116]:
data = pd.read_csv('data/fortune1000.csv', index_col='Rank')
sectors = data.groupby('Sector')
data.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [117]:
# new dataframe, used to store data
df = pd.DataFrame(columns=data.columns)
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

In [118]:
# highest revenue for each sector

In [119]:
for sector, value in sectors:
    highest_revenue_company_in_group = value.nlargest(1, 'Revenue')
    df = df.append(highest_revenue_company_in_group)

In [120]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
109,McDonald’s,"Hotels, Resturants & Leisure",Food Services,"Oak Brook, IL",25413,4529,420000
34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
126,Alcoa,Materials,Metals,"New York, NY",22534,-322,60000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [121]:
cities = data.groupby('Location')

In [122]:
df = pd.DataFrame(columns=data.columns)
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

In [123]:
for city, value in cities:
    highest_revenue_in_city = value.nlargest(1, 'Revenue')
    df = df.append(highest_revenue_in_city)

In [124]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
138,Abbott Laboratories,Health Care,Medical Products and Equipment,"Abbott Park, IL",20661,4423,74000
169,Goodyear Tire & Rubber,Motor Vehicles & Parts,Motor Vehicles and Parts,"Akron, OH",16443,307,66000
288,Air Products & Chemicals,Chemicals,Chemicals,"Allentown, PA",9895,1278,19550
830,Benchmark Electronics,Technology,Semiconductors and Other Electronic Components,"Angleton, TX",2541,95,10500
374,Casey’s General Stores,Retailing,Specialty Retailers: Other,"Ankeny, IA",7052,181,22408
915,Domino’s Pizza,"Hotels, Resturants & Leisure",Food Services,"Ann Arbor, MI",2217,193,11900
596,Colfax,Industrials,Industrial Machinery,"Annapolis Junction, MD",3967,168,17087
215,Land O’Lakes,"Food, Beverages & Tobacco",Food Consumer Products,"Arden Hills, MN",13161,308,10000
190,AES,Energy,Utilities: Gas and Electric,"Arlington, VA",14963,306,21000
31,IBM,Technology,Information Technology Services,"Armonk, NY",82461,13190,411798
28,Home Depot,Retailing,Specialty Retailers: Other,"Atlanta, GA",88519,7009,385000
310,Autoliv,Motor Vehicles & Parts,Motor Vehicles and Parts,"Auburn Hills, MI",9170,457,59350
304,Hormel Foods,"Food, Beverages & Tobacco",Food Consumer Products,"Austin, MN",9264,686,20700
181,Whole Foods Market,Food and Drug Stores,Food and Drug Stores,"Austin, TX",15389,536,76300
668,PolyOne,Chemicals,Chemicals,"Avon Lake, OH",3378,145,6900
573,T. Rowe Price,Financials,Securities,"Baltimore, MD",4201,1223,5999
420,Baxalta,Health Care,Pharmaceuticals,"Bannockburn, IL",6149,956,17000
624,Albemarle,Chemicals,Chemicals,"Baton Rouge, LA",3651,335,6963
207,Kellogg,"Food, Beverages & Tobacco",Food Consumer Products,"Battle Creek, MI",13525,614,33577
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
147,Paccar,Motor Vehicles & Parts,Motor Vehicles and Parts,"Bellevue, WA",19115,1604,23000
645,Regal Beloit,Industrials,"Electronics, Electrical Equip.","Beloit, WI",3510,143,26200
134,Whirlpool,Industrials,"Electronics, Electrical Equip.","Benton Harbor, MI",20891,783,97000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
594,Ametek,Technology,"Scientific,Photographic and Control Equipment","Berwyn, PA",3974,591,15400
60,Lockheed Martin,Aerospace & Defense,Aerospace and Defense,"Bethesda, MD",46132,3605,126000
399,Cablevision Systems,Telecommunications,Telecommunications,"Bethpage, NY",6510,175,13549
366,Live Nation Entertainment,Media,Entertainment,"Beverly Hills, CA",7246,-33,12200
453,Regions Financial,Financials,Commercial Banks,"Birmingham, AL",5674,1062,23916
558,MDU Resources Group,Energy,Energy,"Bismarck, ND",4376,-622,8689
...,...,...,...,...,...,...,...
120,Raytheon,Aerospace & Defense,Aerospace and Defense,"Waltham, MA",23247,2074,61000
850,United Refining,Energy,Petroleum Refining,"Warren, PA",2470,82,2997
431,Zimmer Biomet Holdings,Health Care,Medical Products and Equipment,"Warsaw, IN",5998,147,17500
16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
542,Keurig Green Mountain,"Food, Beverages & Tobacco",Beverages,"Waterbury, VT",4520,498,6000
898,MPM Holdings,Chemicals,Chemicals,"Waterford, NY",2289,-83,5000
874,Granite Construction,Engineering & Construction,"Engineering, Construction","Watsonville, CA",2371,61,3200
1000,Briggs & Stratton,Industrials,Industrial Machinery,"Wauwatosa, WI",1895,46,5480
240,Toys “R” Us,Retailing,Specialty Retailers: Other,"Wayne, NJ",11802,-130,62000
785,B/E Aerospace,Aerospace & Defense,Aerospace and Defense,"Wellington, FL",2730,286,10057
383,AK Steel Holding,Materials,Metals,"West Chester, OH",6693,-509,8500
829,Platform Specialty Products,Chemicals,Chemicals,"West Palm Beach, FL",2542,-309,8200
996,New York Community Bancorp,Financials,Commercial Banks,"Westbury, NY",1902,-47,3448
456,Ingredion,"Food, Beverages & Tobacco",Food Production,"Westchester, IL",5621,402,11500
439,TravelCenters of America,Retailing,Specialty Retailers: Other,"Westlake, OH",5851,28,18450
396,Terex,Industrials,Construction and Farm Machinery,"Westport, CT",6543,146,20400
847,ITT,Industrials,Industrial Machinery,"White Plains, NY",2486,352,9700
389,Spirit AeroSystems Holdings,Aerospace & Defense,Aerospace and Defense,"Wichita, KS",6644,789,15200
849,Tops Holding,Food and Drug Stores,Food and Drug Stores,"Williamsville, NY",2472,-62,14800
674,Westinghouse Air Brake Technologies,Industrials,Industrial Machinery,"Wilmerding, PA",3308,399,13000
101,DuPont,Chemicals,Chemicals,"Wilmington, DE",27940,1953,52000
607,Fastenal,Retailing,Specialty Retailers: Other,"Winona, MN",3869,516,20746
266,Reynolds American,"Food, Beverages & Tobacco",Tobacco,"Winston-Salem, NC",10675,3253,5650
678,Skyworks Solutions,Technology,Semiconductors and Other Electronic Components,"Woburn, MA",3258,798,6700
172,Health Net,Health Care,Health Care: Insurance and Managed Care,"Woodland Hills, CA",16244,186,8584
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
506,Hanover Insurance Group,Financials,Insurance: Property and Casualty (Stock),"Worcester, MA",5034,332,4800
764,Penn National Gaming,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Wyomissing, PA",2838,1,18204
773,Bon-Ton Stores,Retailing,General Merchandisers,"York, PA",2790,-57,24100
932,Herman Miller,Household Products,"Home Equipment, Furnishings","Zeeland, MI",2142,98,7510